services:
  router:
    image: ubuntu:latest
    privileged: true
    container_name: router
    hostname: router
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      external_net:
        ipv4_address: 10.100.10.27
      internal_net:
        ipv4_address: 192.168.70.27
    command: >
      bash -c "
        export DEBIAN_FRONTEND=noninteractive &&
        apt update &&
        apt install -y iptables iproute2 iputils-ping net-tools dnsutils traceroute curl wget snort &&
       echo 1 > /proc/sys/net/ipv4/ip_forward &&
        iptables -I FORWARD -j NFQUEUE --queue-num 0 &&
        echo '=== Configuring Snort 2.9 ===' &&
        mkdir -p /var/log/snort &&
        sed -i '/ipvar HOME_NET/c\ipvar HOME_NET 192.168.70.0/24' /etc/snort/snort.conf &&
        sed -i '/ipvar EXTERNAL_NET/c\ipvar EXTERNAL_NET 10.100.10.0/24' /etc/snort/snort.conf &&
        echo -e 'alert tcp any any -> 192.168.70.0/24 1:65535 (msg: \"Attempted port scan\"; flags:S; detection_filter:track by_src, count 500, seconds 30; sid:1000001; rev:1;)
        alert tcp any any -> 192.168.70.0/24 1:65535 (msg: \"Attempted XMAS scan (os-probing)\"; flags:FPU; detection_filter:track by_src, count 10, seconds 10; sid:1000002; rev:1;)
        alert tcp any any -> 192.168.70.0/24 any (msg:\"DDOS attack\"; flow:established,to_server; threshold: type threshold, track by_src, count 100, seconds 3; sid:1000003; rev:1;)
        alert tcp any any -> 192.168.70.4 3000 (msg:\"SQLi in JSON password field (1=1 or --)\"; flow:to_server,established; content:\"POST /rest/user/\"; nocase; pcre:\"/\\\"password\\\"\\s*:\\s*\\\"[^\\\"]*(?:--|1\s*=\\s*1)[^\\\"]*\\\"/i\"; classtype:web-application-attack; sid:1000061; rev:1;)' >> /etc/snort/rules/local.rules &&
        echo 'Router configured successfully' &&
        tail -f /dev/null
      "

  external_host:
    image: kalilinux/kali-rolling
    container_name: kali
    hostname: kali_attacker
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    cap_add:
      - ALL
    networks:
      external_net:
        ipv4_address: 10.100.10.3
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro    # X11 socket
    - /dev/shm:/dev/shm                   # bigger shared memory avoids crashes
    - ./tools/certs:/certs:ro             # importing CA
    - ./tmp/logs:/logs:rw
    - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: >
      bash -c "
        apt update &&
        apt install -y iproute2 iputils-ping net-tools curl dnsutils traceroute wget slowloris nmap sqlmap &&
        ip route add 192.168.70.0/24 via 10.100.10.27 &&
        echo 'External host configured' &&
        apt update && apt install -y firefox-esr &&
        firefox &&
        tail -f /dev/null
      "

  web_host:
    image: bkimminich/juice-shop
    container_name: juice_shop
    hostname: juice_shop
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      internal_net:
        ipv4_address: 192.168.70.4
    ports:
      - "8080:3000"


  internal_host:
    image: ubuntu:latest
    container_name: internal_host
    hostname: internal_host
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      internal_net:
        ipv4_address: 192.168.70.5
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro    # X11 socket
    - /dev/shm:/dev/shm                   # bigger shared memory avoids crashes
    - ./tools/certs:/certs:ro             # importing CA
    - ./tmp/logs:/logs:rw
    - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
  # Do NOT mount a profile volume here if you want a brand-new profile each run
    command: >
      bash -c "
        apt update &&
        apt install -y iproute2 iputils-ping net-tools curl &&
        ip route add 10.100.10.0/24 via 192.168.70.27 &&
        echo 'Internal host configured' &&
        tail -f /dev/null
      "

networks:
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.10.0/24
          gateway: 10.100.10.1

  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
