services:
  router:
    image: router
    privileged: true
    container_name: router
    hostname: router
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      external_net:
        ipv4_address: 10.100.10.27
      internal_net:
        ipv4_address: 192.168.70.27
    command: >
      bash -c "
        export DEBIAN_FRONTEND=noninteractive &&
        apt update &&
        apt install -y iptables iproute2 iputils-ping net-tools dnsutils traceroute curl wget snort &&
       echo 1 > /proc/sys/net/ipv4/ip_forward &&
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
        iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT &&
        iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
        iptables -A FORWARD -i eth0 -o eth1 -d 192.168.70.4 -j ACCEPT &&
        echo '=== Configuring Snort 2.9 ===' &&
        mkdir -p /var/log/snort &&
        echo 'Router configured successfully' &&
        tail -f /dev/null
      "

  external_host:
    image: kali
    container_name: kali
    hostname: kali_attacker
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    cap_add:
      - ALL
    networks:
      external_net:
        ipv4_address: 10.100.10.3
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro    # X11 socket
    - /dev/shm:/dev/shm                   # bigger shared memory avoids crashes
    - ./tools/certs:/certs:ro             # importing CA
    - ./tmp/logs:/logs:rw
    - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: >
      bash -c "
        apt update &&
        apt install -y iproute2 iputils-ping net-tools curl dnsutils traceroute wget &&
        ip route add 192.168.70.0/24 via 10.100.10.27 &&
        echo 'External host configured' &&
        apt update && apt install -y firefox-esr &&
        tail -f /dev/null
      "

  web_host:
    image: bkimminich/juice-shop
    container_name: juice_shop
    hostname: juice_shop
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      internal_net:
        ipv4_address: 192.168.70.4
    ports:
      - "8080:3000"


  internal_host:
    image: internal_host
    container_name: internal_host
    hostname: internal_host
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    networks:
      internal_net:
        ipv4_address: 192.168.70.5
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro    # X11 socket
    - /dev/shm:/dev/shm                   # bigger shared memory avoids crashes
    - ./tools/certs:/certs:ro             # importing CA
    - ./tmp/logs:/logs:rw
    - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
  # Do NOT mount a profile volume here if you want a brand-new profile each run
#    command: >
#      bash -c "
#        apt update &&
#        apt install -y iproute2 iputils-ping net-tools curl &&
#        ip route add 10.100.10.0/24 via 192.168.70.27 &&
#        echo 'Internal host configured' &&
#        tail -f /dev/null
#      "

networks:
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.10.0/24
          gateway: 10.100.10.1

  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
